### ISSUE TITLE
Instructables link in README.md points to GitHub

### ISSUE THREAD

**Issue by kf6spf** [Short-bus/pilomar#29]
Hi ...

The link at the bottom of the README file:

`The physical telescope, mechanism and dome is buildable from the Instructables page. [https://github.com/Short-bus/pilomar]`

... points back to GitHub instead of the Instructables page:

[https://www.instructables.com/Pi-lomar-3D-Printed-Working-Miniature-Observatory-/](https://www.instructables.com/Pi-lomar-3D-Printed-Working-Miniature-Observatory-/)

**Comment by Short-bus** [comment]
Thanks. Changed the link as you suggested.
